{% set version = "3.10.0" %}

package:
  name: geos
  version: {{ version }}

source:
  url: http://download.osgeo.org/geos/geos-{{ version }}.tar.bz2
  sha256: 097d70e3c8f688e59633ceb8d38ad5c9b0d7ead5729adeb925dbc489437abe13

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    # pretty poor backcompat.  SO name changes each release.
    # https://abi-laboratory.pro/tracker/timeline/geos/
    - {{ pin_subpackage('geos', max_pin='x.x.x') }}

requirements:
  build:
    - cmake  # [win]
    - ninja  # [win]
    - automake  # [not win]
    - libtool  # [not win]
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - geos-config --version  # [not win]

about:
  home: https://trac.osgeo.org/geos/
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Geometry Engine - Open Source
  description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the Java Topology
    Suite (JTS). As such, it aims to contain the complete functionality of
    JTS in C++.
  doc_url: https://trac.osgeo.org/geos/
  dev_url: https://git.osgeo.org/gitea/geos/geos

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - gillins
    - msarahan
    - mwtoews
    - xylar
